# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build and test

on:
  push:
    branches: [ "avdeev/tests" ]
  pull_request:
    branches: [ "avdeev/tests" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout avdeev/tests branch
      uses: actions/checkout@v4
      with:
        ref: 'avdeev/tests'
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore Homeworks/UnitTests/src
    - name: Build
      run: dotnet build Homeworks/UnitTests/src --no-restore
    - name: Test
      run: dotnet test Homeworks/UnitTests/src --no-build --verbosity normal
